### ISSUE TITLE
Can't run without --variant=devdebug --appId=com.paceprogrammer.podotodo.dev

### ISSUE THREAD

**Issue by putuoka** [RadiRS/rn-podotodo#26]
Hi, I just wanna know what makes this can't run without --variant=devdebug --appId=com.paceprogrammer.podotodo.dev ?
i tried with `npx react-native run-android` didn't work the i tried with `npx react-native run-android --variant=devdebug --appId=com.paceprogrammer.podotodo.dev` and working good.

**Comment by RadiRS** [comment]
Hi @putuoka , thank you for using this project.
About your problem is because in this project we are using 3 variant build `dev`, `stag` and `prod` and each variant have 2 config for debug & release.  Example --variant=devDebug and --variant=devRelease

In `npx react-native run-android` usually only have one config for debug & release this generate from `npx react-native-init`

You can read more about this config in this article [Environment Config](https://medium.com/simform-engineering/how-to-set-up-different-environments-in-react-native-9f7902ebf282)

**Comment by putuoka** [comment]
> Hi @putuoka , thank you for using this project. About your problem is because in this project we are using 3 variant build `dev`, `stag` and `prod` and each variant have 2 config for debug & release. Example --variant=devDebug and --variant=devRelease
> 
> In `npx react-native run-android` usually only have one config for debug & release this generate from `npx react-native-init`
> 
> You can read more about this config in this article [Environment Config](https://medium.com/simform-engineering/how-to-set-up-different-environments-in-react-native-9f7902ebf282)

Mantaps. Thanks Bro
